### ISSUE TITLE
Tracking - nieprawidłowe formaty daty zdarzeń

### ISSUE THREAD

**Issue by Wojtu204** [allegro/allegro-api#10195]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Przy pobieraniu historii przesyłki z zasobu order/carriers/{carrierId}/tracking daty zdarzeń dla jednej przesyłki występują w różnych formatach (szczegóły na załączonym zrzucie). 
Jest to niepoprawne zachowanie, które powoduje błędy przy przetwarzaniu daty zdarzeń z formatu, jaki otrzymujemy w odpowiedzi z API na nasz wewnętrzny format daty, a to przekłada się na błędy obsłudze statusów tych przesyłek.
W związku z tym proszę o poprawę działania API, albo przekazywanych od przewoźnika danych w taki sposób, aby daty trzymały zadeklarowany format dla wszystkich czasów wystąpienia zdarzenia.
Przykładowe traca-id: 22e08846bbe255ac
![image](https://github.com/user-attachments/assets/56f69327-b99b-4037-a8f1-f2ed3ddaebef)

**Comment by Lukasz-Zurek** [comment]
Nie odnotowaliśmy problemów w tym zakresie. Zwracanie dwóch cyfr 00Z, lub trzech 000Z - jest zgodne z opisem [standardu ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) _There is no limit on the number of decimal places for the decimal fraction. However, the number of decimal places needs to be agreed to by the communicating parties_ 

Przykłady, które oznaczyłeś zieloną ramką, mają milisekundy (część po kropce). Przykład w czerwonej ramce ma dokładność tylko sekund. Nie generujemy 0 po przecinku, bo to nie niesie żadnych informacji. Widocznie wydarzenie miało miejsce dokładnie w określonej sekundzie (bez milisekund).

Niemniej jednak j.w. oba podejścia są zgodne z ISO 8601.

**Comment by Wojtu204** [comment]
Problem nie dotyczy niezgodności daty z formatem ISO, tylko stosowanie dwóch różnych formatów w tej samej liście wydarzeń. 
Tak jak pisałem - ma to znaczenie do automatu, ponieważ podczas przygotowania mechanizmu konwersji podajemy format daty wejściowej - w przypadku niezgodności danych wejściowych z zadeklarowanym formatem serwis zwraca błąd wykonania usługi. 
Zatem zawarcie milisekund z wartością 000, mimo, że teoretycznie nie niesie żadnej informacji, pozwala na utrzymanie spójności w formacie zwracanych danych - co zresztą znajduje odzwierciedlenie w cytowanym fragmencie standardu ISO: **However, the number of decimal places needs to be agreed to by the communicating parties**
Wskazanie formatu w dokumentacji uważam za takie właśnie uzgodnienie, w oparciu, o które zostały przygotowane serwisy  przetwarzające tą odpowiedź.
W związku z powyższym pożądanym jest albo wysyłanie milisekund zawsze, nawet jeśli mają wartość 000 (tak jak ma to miejsce w innych serwisach, które mają zadeklarowane przekazywanie daty w formacie yyyy-MM-ddTHH:mm:ss.SSS), albo rezygnacja z przekazywania ich w ogóle i zmiana deklarowanego formatu zwracanych danych, jeśli  milisekundy raz mają się pojawiać, a raz nie i tym samym generować błędy w procesowaniu odpowiedzi z API.

**Comment by Lukasz-Zurek** [comment]
@Wojtu204 Dziękuję Ci za kontekst i nakreślenie realnego problemu. Chcąc ułatwiać i optymalizować API, nie pozostaniemy obojętni i postaramy się to ujednolicić - przekazałem ten temat do odpowiedniego zespołu. Proszę jednak o cierpliwość. Jak tylko uzyskam bardziej szczegółowe informacje, dam oczywiście znać.

**Comment by Wojtu204** [comment]
Dziękuję :)
