### ISSUE TITLE
Problem z device flow

### ISSUE THREAD

**Issue by tomek66m** [allegro/allegro-api#4393]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

curl -X POST \
  'https://allegro.pl/auth/oauth/device' \
  -H 'Authorization: Basic ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id=11111111111111111111'
Po Basic wstawiam zakodowany w base64 string clientid:clientsecret, lecz to nie przynosi żadnego efektu

Gdy próbuje dokonać autoryzacji to otrzymają taki response.
Tak wygląda polecenie curl. Docelowo projekt robię w Pythonie, ale z racji tego, że tam dostaję taki response to testuję zapytanie w curl online.

**Comment by Lukasz-Zurek** [comment]
Nie podesłałeś wspomnianego response. Na pierwszy rzut oka wszystko wygląda prawidłowo, nie mając jednak szczegółowych danych, które wprowadzasz, trudno będzie to zweryfikować. Dlatego proszę podeślij nam poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) pełen request, który przesyłasz. W zgłoszeniu dodaj proszę nr postu z GitHub - 4393.

**Comment by tomek66m** [comment]
Przesłałem zgłoszenie

**Comment by Lukasz-Zurek** [comment]
@tomek66m Dziękuję. Zweryfikuję zgłoszenie i wrócę z odpowiedzią.

**Comment by tomek66m** [comment]
Dodam jeszcze, że korzystam z allegro sandbox

**Comment by tomek66m** [comment]
Dziękuję, już załatwiłem problem. Podawałem zły adres url

**Comment by Lukasz-Zurek** [comment]
@tomek66m Dokładnie tak, błędny był adres url.

**Comment by KKowalewski24** [comment]
Właściwie to mam analogiczny problem, język programowania również python, środowisko Allegro sandbox. Pomimo wielu prób i testowania również w online CURL zawsze zwraca mi HTTP 401. Przy rejestracji aplikacji wybrałem typ DEVICE. Poniżej pozwolę sobie umieścić fragment kodu, który obrazuje mój problem. 
```import base64

import requests

# TODO INSERT ClientId and ClientSecret
ClientID = ""
ClientSecret = ""


def main() -> None:
    base_url = "https://allegro.pl.allegrosandbox.pl/auth/oauth/device"
    encoded_id_secret = base64.b64encode((ClientID + ":" + ClientSecret).encode("ascii"))
    print(encoded_id_secret)

    response = requests.post(
        base_url,
        headers={
            "Authorization": "Basic %s" % encoded_id_secret,
            "Content-Type": "application/x-www-form-urlencoded",
        },
        data={"client_id": ClientID}
    )
    print(response)


if __name__ == '__main__':
    main()
```
Za pomoc będe bardzo wdzięczny bo już nie wiem co mógłbym zrobić aby zaczeło to działać. Testowałem moje  CliendId i ClientSecret dla Client_credentials flow i działa także powinny być one poprawne.

**Comment by Lukasz-Zurek** [comment]
@KKowalewski24 Ze względu na dużą liczbę jezyków programowania, nie świadczymy wsparcia dla każdego z nich.

Być może na naszym forum znajdzie się użytkownik, który miał już taki problem i będzie mógł Tobie pomóc.

**Comment by tomek66m** [comment]
clientId = 'tu wprowadz swoj client id'
        semi = ':'
        clientSecret = 'tu wprowadz swoj client secret'

        string_to_encode = clientId + ':' + clientSecret

        string_to_encode_bytes = string_to_encode.encode('UTF-8')
        base64_bytes = base64.b64encode(string_to_encode_bytes)
        
        test = 'Basic ' + str(base64_bytes, 'utf-8')



        headersObj = {'Authorization' : test, 'Content-Type' : 'application/x-www-form-urlencoded'}
        response = requests.post("https://allegro.pl.allegrosandbox.pl/auth/oauth/device", data='client_id=' + clientId, headers=headersObj)

**Comment by KKowalewski24** [comment]
@tomek66m Dziękuje za kod i pomoc. Response zwraca HTTP 200 czyli jest wszystko git. Z tego co widzie co źle zrobiłem to
* źle kodowałem tego stringa do bytes
* przekazywałem data jako Dictionary a nie jako string
