### ISSUE TITLE
WZA brak tracking DPD

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#6584]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,

Czy mogą Państwo zweryfikować śledzenie przesyłek dla WZA DPD? 

`GET https://api.allegro.pl/order/carriers/ALLEGRO/tracking?waybill={id} || trace-id:113a2e48dd90f392`
`GET https://api.allegro.pl/order/carriers/ALLEGRO/tracking?waybill={id} || trace-id:905c334077d18a28`

Otrzymuję NULL w trackingDetails
`{"carrierId":"ALLEGRO","waybills":[{"waybill":"{id}","trackingDetails":null}]}`

Śledzenie od 08.2022 jest dla wszystkich kurierów
https://github.com/allegro/allegro-api/issues/6020

Dziękuję

**Comment by MaciejFrackowiak** [comment]
Zgodnie z przytoczonym [newsem](https://github.com/allegro/allegro-api/issues/6020) jako {carrierId} musisz podać właściwego przewoźnika - jeśli masz przesyłkę DPD, to powinno tam widnieć DPD, a nie Allegro.

**Comment by Radeq** [comment]
@MaciejFrackowiak, dziękuję, przegapiłem to + miałem jeszcze nagłówek `application/vnd.allegro.beta.v1+json`
